### PR TITLE
Ob 358 display initial date

### PR DESCRIPTION
**Pull request by charleskoehl**
This corrects the initial display of the date within the input when its data-bound value is already set when the input is ready. To elaborate, this element has two values: The "value" which is the native input's value displayed inside the input, and the "data" value which is stored in the "dataData" property and reflected to the "data-data" attribute. You can bind the "data-data" attribute using markup, either 1-way or 2-way.

This change makes sure that when the input is initially displayed, and has a value for the "data-data" attribute, it sets its native "value" to the correctly-formatted date based on the value of formats.data.

### CODE REVIEW

**Comment by 311chaos** [comment]
A little confused on the dataData, but other than that, this looks good.

**Comment by charleskoehl** [comment]
@311chaos: The reason for the "dataData" property name is that the **name** of any Polymer property you add to a "type extension custom element" such as ll-date-input has to begin with the word "data" if you want to reflect it to its corresponding "data-___" attribute. In other words, you cannot reflect a Polymer property such as "myVariable" to the "my-variable" attribute of a type extension custom element."

The reason I called it "dataData" instead of "dataIso" is because the format of the value is customizable and only defaults to ISO format.

**Comment by 311chaos** [comment]
I figured it was something like that. Did you ever find that documented anywhere?

**Comment by charleskoehl** [comment]
No, I found out the hard way.

**Comment by 311chaos** [comment]
Ha. Also what I figured. :)

**Pull request merged**
